# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pmd.github.io
baseurl:
title: PMD
author: PMD
description: PMD is a source code analyzer. It finds unused variables, empty catch blocks, unnecessary object creation, and so forth.
keywords: PMD,Java,Salesforce.com Apex,Code Analyzer,Clean Code,Software Development
copyright: 'Copyright &copy; 2020 PMD. All Rights Reserved.'
credits: 'Credits: <a href="https://github.com/swcool/landing-page-theme">Landing Page Theme</a>, based on free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

exclude:
    - .gitignore
    - README.md
    - vendor

# to speed up local builds, exclude the following, too:
#    - 'pmd-5*'
#    - 'pmd-6*'

# ----------------------- #
#     PMD vars            #
# ----------------------- #
pmd:
  latestVersion: 6.35.0
  latestVersionDate: 29-May-2021
  downloads:
      - version: 6.34.0
        date: 24-April-2021
      - version: 6.33.0
        date: 27-March-2021
      - version: 6.32.0
        date: 27-February-2021

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/pmd/pmd
