# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://pmd.github.io
baseurl: ''
title: PMD
author: PMD
description: PMD is a source code analyzer. It finds unused variables, empty catch blocks, unnecessary object creation, and so forth.
keywords: PMD,Java,Salesforce.com Apex,Code Analyzer,Clean Code,Software Development
copyright: 'Copyright &copy; 2025 PMD. All Rights Reserved.'
credits: 'Credits: <a href="https://github.com/swcool/landing-page-theme">Landing Page Theme</a>, based on free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

exclude:
    - .gitignore
    - build-docs.sh
    - README.md
    - vendor
    - node_modules
    - scripts
    - package.json
    - package-lock.json

# ----------------------- #
#     PMD vars            #
# ----------------------- #
pmd:
  # the first version is the latest
  # all the versions are available in the download section
  versions:
    - version: 7.17.0
      date: 12-September-2025
    - version: 7.16.0
      date: 25-July-2025
    - version: 7.15.0
      date: 27-June-2025
    - version: 7.14.0
      date: 30-May-2025

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: false
  # selectively enable kramdown parsing for block html elements with attribute 'markdown="block"'
  # see https://kramdown.gettalong.org/syntax.html
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/pmd/pmd
